{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "mount_file_id": "1_udn4w_AkgwzEkdsE_pWvGxwJKsCDNoe",
      "authorship_tag": "ABX9TyPzR0FwXcdHScPTeQ6n3VXI",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/gauravbhalar95/Telegram_bot/blob/main/Recipe.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "!pip install pyTelegramBotAPI google-api-python-client oauth2client"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "yo_Qa2PSdNTP",
        "outputId": "ebc0dcc4-e71f-4daf-e557-78ab81c96d91"
      },
      "execution_count": 3,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Collecting pyTelegramBotAPI\n",
            "  Downloading pytelegrambotapi-4.22.1-py3-none-any.whl.metadata (48 kB)\n",
            "\u001b[?25l     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m0.0/48.2 kB\u001b[0m \u001b[31m?\u001b[0m eta \u001b[36m-:--:--\u001b[0m\r\u001b[2K     \u001b[91m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[90m╺\u001b[0m\u001b[90m━━━━━\u001b[0m \u001b[32m41.0/48.2 kB\u001b[0m \u001b[31m1.2 MB/s\u001b[0m eta \u001b[36m0:00:01\u001b[0m\r\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m48.2/48.2 kB\u001b[0m \u001b[31m923.3 kB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hRequirement already satisfied: google-api-python-client in /usr/local/lib/python3.10/dist-packages (2.137.0)\n",
            "Requirement already satisfied: oauth2client in /usr/local/lib/python3.10/dist-packages (4.1.3)\n",
            "Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from pyTelegramBotAPI) (2.32.3)\n",
            "Requirement already satisfied: httplib2<1.dev0,>=0.19.0 in /usr/local/lib/python3.10/dist-packages (from google-api-python-client) (0.22.0)\n",
            "Requirement already satisfied: google-auth!=2.24.0,!=2.25.0,<3.0.0.dev0,>=1.32.0 in /usr/local/lib/python3.10/dist-packages (from google-api-python-client) (2.27.0)\n",
            "Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /usr/local/lib/python3.10/dist-packages (from google-api-python-client) (0.2.0)\n",
            "Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5 in /usr/local/lib/python3.10/dist-packages (from google-api-python-client) (2.19.1)\n",
            "Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.10/dist-packages (from google-api-python-client) (4.1.1)\n",
            "Requirement already satisfied: pyasn1>=0.1.7 in /usr/local/lib/python3.10/dist-packages (from oauth2client) (0.6.0)\n",
            "Requirement already satisfied: pyasn1-modules>=0.0.5 in /usr/local/lib/python3.10/dist-packages (from oauth2client) (0.4.0)\n",
            "Requirement already satisfied: rsa>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from oauth2client) (4.9)\n",
            "Requirement already satisfied: six>=1.6.1 in /usr/local/lib/python3.10/dist-packages (from oauth2client) (1.16.0)\n",
            "Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /usr/local/lib/python3.10/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (1.63.2)\n",
            "Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0.dev0,>=3.19.5 in /usr/local/lib/python3.10/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (3.20.3)\n",
            "Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /usr/local/lib/python3.10/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (1.24.0)\n",
            "Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0.dev0,>=1.32.0->google-api-python-client) (5.4.0)\n",
            "Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /usr/local/lib/python3.10/dist-packages (from httplib2<1.dev0,>=0.19.0->google-api-python-client) (3.1.2)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->pyTelegramBotAPI) (3.3.2)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->pyTelegramBotAPI) (3.7)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->pyTelegramBotAPI) (2.0.7)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->pyTelegramBotAPI) (2024.7.4)\n",
            "Downloading pytelegrambotapi-4.22.1-py3-none-any.whl (261 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m261.0/261.0 kB\u001b[0m \u001b[31m2.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hInstalling collected packages: pyTelegramBotAPI\n",
            "Successfully installed pyTelegramBotAPI-4.22.1\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "J80LldxXdJHC",
        "outputId": "b701373b-6808-4df5-b8dc-6756d6da6ad3"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "Exception in thread Thread-13 (periodic_check):\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/threading.py\", line 1016, in _bootstrap_inner\n",
            "    self.run()\n",
            "  File \"/usr/lib/python3.10/threading.py\", line 953, in run\n",
            "    self._target(*self._args, **self._kwargs)\n",
            "  File \"<ipython-input-10-97ce82d0dc08>\", line 100, in periodic_check\n",
            "  File \"<ipython-input-10-97ce82d0dc08>\", line 85, in check_for_new_posts\n",
            "  File \"<ipython-input-10-97ce82d0dc08>\", line 94, in notify_new_post\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 1766, in send_message\n",
            "    apihelper.send_message(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/apihelper.py\", line 273, in send_message\n",
            "    return _make_request(token, method_url, params=payload, method='post')\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/apihelper.py\", line 168, in _make_request\n",
            "    json_result = _check_result(method_name, result)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/apihelper.py\", line 195, in _check_result\n",
            "    raise ApiTelegramException(method_name, result, result_json)\n",
            "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found\n",
            "2024-08-16 18:49:34,757 (__init__.py:1106 MainThread) ERROR - TeleBot: \"Infinity polling exception: Got an unexpected keyword argument q\"\n",
            "ERROR:TeleBot:Infinity polling exception: Got an unexpected keyword argument q\n",
            "2024-08-16 18:49:34,761 (__init__.py:1108 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 1101, in infinity_polling\n",
            "    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 1189, in polling\n",
            "    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 1264, in __threaded_polling\n",
            "    raise e\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 1226, in __threaded_polling\n",
            "    self.worker_pool.raise_exceptions()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/util.py\", line 150, in raise_exceptions\n",
            "    raise self.exception_info\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/util.py\", line 93, in run\n",
            "    task(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 8822, in _run_middlewares_and_handler\n",
            "    result = handler['function'](message)\n",
            "  File \"<ipython-input-10-97ce82d0dc08>\", line 66, in handle_message\n",
            "    posts = fetch_blog_posts(query)\n",
            "  File \"<ipython-input-10-97ce82d0dc08>\", line 37, in fetch_blog_posts\n",
            "    request = blogger_service.posts().list(blogId=BLOG_ID, q=query, fetchBodies=True)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/googleapiclient/discovery.py\", line 1099, in method\n",
            "    raise TypeError(\"Got an unexpected keyword argument {}\".format(name))\n",
            "TypeError: Got an unexpected keyword argument q\n",
            "\"\n",
            "ERROR:TeleBot:Exception traceback:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 1101, in infinity_polling\n",
            "    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 1189, in polling\n",
            "    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 1264, in __threaded_polling\n",
            "    raise e\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 1226, in __threaded_polling\n",
            "    self.worker_pool.raise_exceptions()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/util.py\", line 150, in raise_exceptions\n",
            "    raise self.exception_info\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/util.py\", line 93, in run\n",
            "    task(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 8822, in _run_middlewares_and_handler\n",
            "    result = handler['function'](message)\n",
            "  File \"<ipython-input-10-97ce82d0dc08>\", line 66, in handle_message\n",
            "    posts = fetch_blog_posts(query)\n",
            "  File \"<ipython-input-10-97ce82d0dc08>\", line 37, in fetch_blog_posts\n",
            "    request = blogger_service.posts().list(blogId=BLOG_ID, q=query, fetchBodies=True)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/googleapiclient/discovery.py\", line 1099, in method\n",
            "    raise TypeError(\"Got an unexpected keyword argument {}\".format(name))\n",
            "TypeError: Got an unexpected keyword argument q\n",
            "\n",
            "2024-08-16 18:49:51,494 (__init__.py:1106 MainThread) ERROR - TeleBot: \"Infinity polling exception: Got an unexpected keyword argument q\"\n",
            "ERROR:TeleBot:Infinity polling exception: Got an unexpected keyword argument q\n",
            "2024-08-16 18:49:51,498 (__init__.py:1108 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 1101, in infinity_polling\n",
            "    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 1189, in polling\n",
            "    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 1264, in __threaded_polling\n",
            "    raise e\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 1226, in __threaded_polling\n",
            "    self.worker_pool.raise_exceptions()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/util.py\", line 150, in raise_exceptions\n",
            "    raise self.exception_info\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/util.py\", line 93, in run\n",
            "    task(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 8822, in _run_middlewares_and_handler\n",
            "    result = handler['function'](message)\n",
            "  File \"<ipython-input-10-97ce82d0dc08>\", line 66, in handle_message\n",
            "    posts = fetch_blog_posts(query)\n",
            "  File \"<ipython-input-10-97ce82d0dc08>\", line 37, in fetch_blog_posts\n",
            "    request = blogger_service.posts().list(blogId=BLOG_ID, q=query, fetchBodies=True)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/googleapiclient/discovery.py\", line 1099, in method\n",
            "    raise TypeError(\"Got an unexpected keyword argument {}\".format(name))\n",
            "TypeError: Got an unexpected keyword argument q\n",
            "\"\n",
            "ERROR:TeleBot:Exception traceback:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 1101, in infinity_polling\n",
            "    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 1189, in polling\n",
            "    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 1264, in __threaded_polling\n",
            "    raise e\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 1226, in __threaded_polling\n",
            "    self.worker_pool.raise_exceptions()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/util.py\", line 150, in raise_exceptions\n",
            "    raise self.exception_info\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/util.py\", line 93, in run\n",
            "    task(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/telebot/__init__.py\", line 8822, in _run_middlewares_and_handler\n",
            "    result = handler['function'](message)\n",
            "  File \"<ipython-input-10-97ce82d0dc08>\", line 66, in handle_message\n",
            "    posts = fetch_blog_posts(query)\n",
            "  File \"<ipython-input-10-97ce82d0dc08>\", line 37, in fetch_blog_posts\n",
            "    request = blogger_service.posts().list(blogId=BLOG_ID, q=query, fetchBodies=True)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/googleapiclient/discovery.py\", line 1099, in method\n",
            "    raise TypeError(\"Got an unexpected keyword argument {}\".format(name))\n",
            "TypeError: Got an unexpected keyword argument q\n",
            "\n"
          ]
        }
      ],
      "source": [
        "\n",
        "import telebot\n",
        "import googleapiclient.discovery\n",
        "from oauth2client.service_account import ServiceAccountCredentials\n",
        "from telebot import types\n",
        "import time\n",
        "import threading\n",
        "\n",
        "# Replace with your bot's token\n",
        "Token = \"7316963125:AAH_zNBZkaguB4pD8rBmadWg1Iwm9Efm_BI\"\n",
        "\n",
        "bot = telebot.TeleBot(Token)\n",
        "\n",
        "# Blogger API setup\n",
        "BLOG_ID = \"6506022432368434594\"  # Replace with your Blogger blog ID\n",
        "SCOPES = ['https://www.googleapis.com/auth/blogger']\n",
        "\n",
        "# Load credentials from the credentials.json file\n",
        "credentials = ServiceAccountCredentials.from_json_keyfile_name('/content/drive/MyDrive/Json/spiceloversdelight-586791ec0797.json', scopes=SCOPES)\n",
        "\n",
        "blogger_service = googleapiclient.discovery.build('blogger', 'v3', credentials=credentials)\n",
        "\n",
        "# Function to fetch all blog posts with pagination\n",
        "def fetch_all_blog_posts():\n",
        "    posts = []\n",
        "    next_page_token = None\n",
        "    while True:\n",
        "        request = blogger_service.posts().list(blogId=BLOG_ID, pageToken=next_page_token, fetchBodies=True)\n",
        "        response = request.execute()\n",
        "        posts.extend(response.get('items', []))\n",
        "        next_page_token = response.get('nextPageToken')\n",
        "        if not next_page_token:\n",
        "            break\n",
        "    return posts\n",
        "\n",
        "# Function to fetch blog posts based on a query\n",
        "def fetch_blog_posts(query):\n",
        "    request = blogger_service.posts().list(blogId=BLOG_ID, q=query, fetchBodies=True)\n",
        "    response = request.execute()\n",
        "    return response.get('items', [])\n",
        "\n",
        "# Start command handler\n",
        "@bot.message_handler(commands=['start'])\n",
        "def send_welcome(message):\n",
        "    bot.reply_to(message, \"Welcome to the Recipe Bot! 🍽️\\nType 'list' to view available recipes or type an ingredient/recipe name to search.\")\n",
        "\n",
        "# List recipes handler\n",
        "@bot.message_handler(func=lambda message: message.text.lower() == \"list\")\n",
        "def list_recipes(message):\n",
        "    posts = fetch_all_blog_posts()\n",
        "\n",
        "    if posts:\n",
        "        markup = types.InlineKeyboardMarkup()\n",
        "        for post in posts:\n",
        "            title = post.get('title', 'No title')\n",
        "            url = post.get('url', '')\n",
        "            markup.add(types.InlineKeyboardButton(text=title, url=url))\n",
        "\n",
        "        bot.send_message(message.chat.id, \"Here are the available recipes:\", reply_markup=markup)\n",
        "    else:\n",
        "        bot.reply_to(message, \"Sorry, I couldn't find any recipes.\")\n",
        "\n",
        "# Handler to search and display posts based on user query\n",
        "@bot.message_handler(func=lambda message: True)\n",
        "def handle_message(message):\n",
        "    query = message.text.lower()\n",
        "    posts = fetch_blog_posts(query)\n",
        "\n",
        "    if posts:\n",
        "        post = posts[0]  # Get the first matching post\n",
        "        title = post.get('title', 'No title')\n",
        "        snippet = post.get('content', 'No content')[:200]  # Get a snippet of the content\n",
        "        url = post.get('url', '')\n",
        "\n",
        "        response = f\"**{title}**\\n\\n{snippet}...\\n\\nRead more: {url}\"\n",
        "    else:\n",
        "        response = \"Sorry, I couldn't find any recipes matching that query.\"\n",
        "\n",
        "    bot.reply_to(message, response)\n",
        "\n",
        "# Function to check for new posts\n",
        "def check_for_new_posts(last_known_post_id):\n",
        "    new_posts = fetch_all_blog_posts()\n",
        "    latest_post_id = new_posts[0].get('id') if new_posts else None\n",
        "    if latest_post_id != last_known_post_id:\n",
        "        notify_new_post(new_posts[0])\n",
        "        return latest_post_id\n",
        "    return last_known_post_id\n",
        "\n",
        "# Notify user about the new post\n",
        "def notify_new_post(post):\n",
        "    title = post.get('title', 'No title')\n",
        "    url = post.get('url', '')\n",
        "    message = f\"New Recipe Posted! 🍽️\\n\\n**{title}**\\nRead more: {url}\"\n",
        "    bot.send_message(chat_id='-1001524250802', text=message)  # Replace with your chat or channel ID\n",
        "\n",
        "# Periodically check for new posts\n",
        "def periodic_check():\n",
        "    last_known_post_id = None\n",
        "    while True:\n",
        "        last_known_post_id = check_for_new_posts(last_known_post_id)\n",
        "        time.sleep(600)  # Check every 10 minutes\n",
        "\n",
        "# Start the periodic check in a separate thread\n",
        "threading.Thread(target=periodic_check).start()\n",
        "\n",
        "# Start polling\n",
        "bot.infinity_polling()"
      ]
    }
  ]
}